version: 2

project_name: urlbox

before:
  hooks:
    - make ci

builds:
  - id: urlbox
    main: ./cmd/urlbox
    binary: urlbox
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/urlbox/urlbox-cli/internal/version.Version={{.Version}}
      - -X github.com/urlbox/urlbox-cli/internal/version.Commit={{.ShortCommit}}
      - -X github.com/urlbox/urlbox-cli/internal/version.Date={{.Date}}

archives:
  - id: default
    ids:
      - urlbox
    name_template: "urlbox_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - id: packages
    package_name: urlbox
    vendor: Urlbox
    homepage: https://urlbox.com
    maintainer: Urlbox <support@urlbox.com>
    description: Official CLI for the Urlbox screenshot and web automation API
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

brews:
  - name: urlbox
    repository:
      owner: urlbox
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://urlbox.com
    description: Official CLI for the Urlbox screenshot and web automation API
    license: MIT
    install: |
      bin.install "urlbox"

scoops:
  - name: urlbox
    repository:
      owner: urlbox
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: bucket
    homepage: https://urlbox.com
    description: Official CLI for the Urlbox screenshot and web automation API
    license: MIT

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: urlbox
    name: urlbox-cli
  prerelease: auto
